// Sample Event Data
const events = [
  {
    event_id: "EVT001",
    name: "Lip Balm Making Workshop",
    description: "Elevate your corporate gathering with our Lip Balm Making Workshop—an experience that blends creativity, team unity, and a touch of glamour! 🌟 Immerse your colleagues in a hands-on journey of crafting personalized lip balms. Our skilled instructors guide the process, unveiling the secrets of silky, nourishing lip care. Picture the joy as your team selects their favorite flavors, blends ingredients, and designs custom labels for their signature lip balms. It’s more than an activity; it’s a delightful fusion of team building and beauty.",
    capacity: 50,
    venue: "Suntect City Singapore",
    event_hour: 2,
    category: "workshop",
    payment: ["vendorgov", "einvoice", "creditcard"],
    image: "public/images/lipbalm.png",
    event_org_id: "ORG100",
    organiser_name: "PartyMojo",
    organiser_website: "https://partymojo.com.sg/",
    organiser_contact: "+65 6569 6992",	
    organiser_email: "Sales@partymojo.com.sg"
  },
  {
    event_id: "EVT002",
    name: "Terrarium Making Workshop",
    description: "Build your own cute miniature garden or forest with this kids friendly terrarium making workshop. It’s pretty, it’s fun, it’s self sustainable. Perfect for team bonding and corporate events.",
    capacity: 50,
    venue: "Suntect City Singapore",
    event_hour: 4,
    category: "workshop",
    payment: ["vendorgov", "einvoice"],
    image: "public/images/terrarium.png",
    event_org_id: "ORG100",
    organiser_name: "PartyMojo",
    organiser_website: "https://partymojo.com.sg/",
    organiser_contact: "+65 6569 6992",	
    organiser_email: "Sales@partymojo.com.sg"
  },
  {
    event_id: "EVT003",
    name: "Balloon Scrupting Workshop",
    description: "Join us for a fun and engaging balloon sculpting workshop. Learn up to 5 simple balloon sculptures.",
    capacity: 120,
    venue: "Suntect City Singapore",
    event_hour: 4,
    category: "workshop",
    payment: ["vendorgov", "einvoice", "creditcard"],
    image: "public/images/balloon.png",
    event_org_id: "ORG100",
    organiser_name: "PartyMojo",
    organiser_website: "https://partymojo.com.sg/",
    organiser_contact: "+65 6569 6992",	
    organiser_email: "Sales@partymojo.com.sg"
  },
  {
    event_id: "EVT004",
    name: "The Royal Chariot",
    description: "Racing against the clock and each other, teams are required to pull together in this inspiring challenge which combines the skills of creativity, innovation and communication. Teams will need to transform their cardboard materials into a life-sized racing chariot, where machine and human-power will work together in harmony. The challenge concludes with the Chariot of Fire, where teams will pull their teammate in their chariots, and race against their opponents.",
    capacity: 150,
    venue: "Expo Singapore",
    event_hour: 4,
    category: "game",
    payment: ["creditcard"],
    image: "public/images/RoyalChariot.jpg",
    event_org_id: "ORG101",
    organiser_name: "Funworks",
    organiser_website: "https://funworks.sg/",
    organiser_contact: "+65 6743 3077",
    organiser_email: "hello@funworks.sg"
  },
  {
    event_id: "EVT005",
    name: "Kingdom Of Power",
    description: "Each team will be given materials and they have to transform them into their life-sized kingdoms, which consist of a fortress, racing chariot, armours, shields and swords. The challenge concludes with a gladiator-themed Grand Parade, followed by the Final Battle where each kingdom pit their strongest fighters against each other.",
    capacity: 60,
    venue: "Kallang Indoor Stadium",
    event_hour: 4,
    category: "game",
    payment: ["vendorgov", "einvoice"],
    image: "public/images/KingdomofPower.jpg",
    event_org_id: "ORG101",
    organiser_name: "Funworks",
    organiser_website: "https://funworks.sg/",
    organiser_contact: "+65 6743 3077",
    organiser_email: "hello@funworks.sg"
  },
  {
    event_id: "EVT006",
    name: "Build and Race",
    description: "Row, row, row your boat, and see if you can make it float! Teams are to make use of the cardboard materials and construct a seaworthy boat. As a finale, teams will take their boats and race against one another, either in a pool or the open sea! This is a challenge where your participants will experience the “impossible” become achievable!",
    capacity: 100,
    venue: "Sentosa",
    event_hour: 8,
    category: "adventure",
    payment: ["einvoice", "creditcard"],
    image: "public/images/BuildandRace.jpg",
    event_org_id: "ORG101",
    organiser_name: "Funworks",
    organiser_website: "https://funworks.sg/",
    organiser_contact: "+65 6743 3077",
    organiser_email: "hello@funworks.sg"
  },
  {
    event_id: "EVT007",
    name: "Food Hunting",
    description: "Given a virtual cash to spend on the hawker center. Share with the team what have you discovered.",
    capacity: 150,
    venue: "Expo Singapore",
    event_hour: 4,
    category: "adventure",
    payment: ["creditcard"],
    image: "public/images/FoodHunting.jpg",
    event_org_id: "ORG102",
    organiser_name: "The Meet Up SG",
    organiser_website: "https://www.themeetupsg.com/",
    organiser_contact: "+65 8793 0476",
    organiser_email: "enquiries@themeetupsg.com"
  },
  {
    event_id: "EVT008",
    name: "Cruise SG",
    description: "4 hours of cruise in SG to enjoy the sea view with tea break.",
    capacity: 50,
    venue: "Cruise Singapore",
    event_hour: 8,
    category: "adventure",
    payment: ["creditcard"],
    image: "public/images/cruise.jpg",
    event_org_id: "ORG102",
    organiser_name: "The Meet Up SG",
    organiser_website: "https://www.themeetupsg.com/",
    organiser_contact: "+65 8793 0476",
    organiser_email: "enquiries@themeetupsg.com"
  },
  {
    event_id: "EVT009",
    name: "Are you the Artist",
    description: "Teaching of drawing and coloring on Canvas.",
    capacity: 50,
    venue: "SOTA",
    event_hour: 4,
    category: "workshop",
    payment: ["creditcard"],
    image: "public/images/art.jpg",
    event_org_id: "ORG102",
    organiser_name: "The Meet Up SG",
    organiser_website: "https://www.themeetupsg.com/",
    organiser_contact: "+65 8793 0476",
    organiser_email: "enquiries@themeetupsg.com"
  },
  {
    event_id: "EVT010",
    name: "Combat Archery Tag",
    description: "Exhilarating and fast-paced game combining archery, paintball and dogdeball that will get your adrenaline pumping.",
    capacity: 1000,
    venue: "Kallang Stadium",
    event_hour: 4,
    category: "game",
    payment: ["creditcard"],
    image: "public/images/combat.jpg",
     event_org_id: "ORG103",
    organiser_name: "FunEmpire",
 organiser_website: "https://www.funempire.com/",
    organiser_contact: "+65 6016 7147",
    organiser_email: "hello@funempire.com"
  },
  {
    event_id: "EVT011",
    name: "Bubble Soccer",
    description: "Bounce your way to victory with the fun-filled action of Bubble Soccer. Bump your opponents without getting a red card.",
    capacity: 1000,
    venue: "Kallang Stadium",
    event_hour: 4,
    category: "game",
    payment: ["creditcard"],
    image: "public/images/bubble.jpg",
     event_org_id: "ORG103",
    organiser_name: "FunEmpire",
 organiser_website: "https://www.funempire.com/",
    organiser_contact: "+65 6016 7147",
    organiser_email: "hello@funempire.com"
  },
  {
    event_id: "EVT012",
    name: "Art Jamming",
    description: "Unleash creativity through an art jam as teams come together to paint and express themselves.",
    capacity: 50,
    venue: "SOTA",
    event_hour: 2,
    category: "workshop",
    payment: ["creditcard"],
    image: "public/images/artjamming.jpg",
     event_org_id: "ORG103",
    organiser_name: "FunEmpire",
 organiser_website: "https://www.funempire.com/",
    organiser_contact: "+65 6016 7147",
    organiser_email: "hello@funempire.com"
  },
  {
    event_id: "EVT013",
    name: "Corporate Dragonboat Teambonding",
    description: "Whether you’re aiming for team cohesion or a competitive race, our Dragonboat Challenge can be customized to meet your goals. Engage in teamwork, strategy, and communication as your team paddles to victory. Ideal for fostering collaboration and camaraderie, this activity culminates in an exhilarating team race that leaves everyone unified.",
    capacity: 200,
    venue: "Sentosa",
    event_hour: 4,
    category: "adventure",
    payment: ["creditcard"],
    image: "public/images/dragonboat.png",
     event_org_id: "ORG104",
    organiser_name: "Focus Adventure",
 organiser_website: "https://focusadventure.com/",
    organiser_contact: "+65 6278 6560",
    organiser_email: "info@FOCUSAdventure.com"
  },
  {
    event_id: "EVT014",
    name: "The Kayaking Challenge",
    description: "Our kayaking expeditions encourage teams to work together, develop leadership skills, and build trust as they paddle through scenic routes.",
    capacity: 200,
    venue: "Sentosa",
    event_hour: 4,
    category: "adventure",
    payment: ["creditcard"],
    image: "public/images/kayak.png",
     event_org_id: "ORG104",
    organiser_name: "Focus Adventure",
 organiser_website: "https://focusadventure.com/",
    organiser_contact: "+65 6278 6560",
    organiser_email: "info@FOCUSAdventure.com"
  }
,
  {
    event_id: "EVT015",
    name: "Team Challenge Pyramic",
    description: "Embark on a thrilling ascent with the TEAM CHALLENGE PYRAMID, a towering 25-meter structure designed to foster unparalleled team cohesion and leadership skills. This unique challenge invites groups of five to navigate an upward spiral to the pyramid’s peak, encountering a series of engaging tasks that demand cooperation, strategic thinking, and mutual support.",
    capacity: 200,
    venue: "Sentosa",
    event_hour: 4,
    category: "adventure",
    payment: ["creditcard"],
    image: "public/images/pyramic.png",
     event_org_id: "ORG104",
    organiser_name: "Focus Adventure",
 organiser_website: "https://focusadventure.com/",
    organiser_contact: "+65 6278 6560",
    organiser_email: "info@FOCUSAdventure.com"
  }
  
];
